#!/bin/sh

# Start cron
cron -L 7

# Some deis containers need an extra entry step
if [ -x /app/bin/entry ]
then
	/app/bin/entry

	exitstatus="$?"

	if [ "$exitstatus" != "0" ]; then
		echo "The entry script failed"
		exit $exitstatus
	fi
fi

# Start the main container process
/app/bin/boot

